name: Install Riff
description: Install Riff in the GitHub Actions environment
author: Determinate Systems
inputs:
  riff_version:
    description: The version of Riff to install
    required: false
    default: "1.0.0"
runs:
  using: composite
  steps:
    # Install Nix
    - uses: cachix/install-nix-action@v17
    # Install Cargo
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    # Install Riff using ./install-riff.sh
    - run: ${{ github.action_path }}/install-riff.sh
      shell: bash
      env:
        RIFF_VERSION: ${{ inputs.riff_version }}
branding:
  icon: music
  color: purple
