name: Install Riff
description: Install Riff in the GitHub Actions environment
author: Determinate Systems
inputs:
  rust_toolchain:
    description: The Rust toolchain to install
    required: false
    default: stable
runs:
  using: composite
  steps:
    - uses: cachix/install-nix-action@v17
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: ${{ github.action_path }}/install-riff.sh
      shell: bash
branding:
  icon: music
  color: purple
