name: Install Riff
description: Install Riff in the GitHub Actions environment
author: Determinate Systems
inputs:
  riff-version:
    description: The version of Riff to install
    required: false
    default: "1.0.3"
runs:
  using: composite
  steps:
    # Install Riff using ./install-riff.sh
    - run: ${{ github.action_path }}/install-riff.sh
      shell: bash
      env:
        RIFF_VERSION: ${{ inputs.riff-version }}
branding:
  icon: music
  color: purple
